# Here you can define all your data sets by using simple YAML syntax.
#
# Documentation for this file format can be found in "The Data Catalog"
# Link: https://kedro.readthedocs.io/en/stable/04_user_guide/04_data_catalog.html

normalized_reviews:
  type: MemoryDataSet
review_vectors:
  type: MemoryDataSet
similar_movies:
  type: MemoryDataSet
test_data:
  type: MemoryDataSet
